# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 17:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机格式错误')], verbose_name='手机号码')),
                ('user_nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=32, verbose_name='密码')),
                ('user_birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('user_gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('user_school', models.CharField(blank=True, max_length=40, null=True, verbose_name='学校')),
                ('user_address', models.CharField(blank=True, max_length=40, null=True, verbose_name='地址')),
                ('user_hometown', models.CharField(blank=True, max_length=43, null=True, verbose_name='籍贯')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
