# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
    ]
