# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 13:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=22, verbose_name='活动名字')),
                ('activity_photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='activity', verbose_name='活动图片地址')),
                ('activity_address', models.URLField(max_length=500, verbose_name='活动链接地址')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('region_name', models.CharField(max_length=22, verbose_name='专区名字')),
                ('region_introduce', models.CharField(max_length=22, verbose_name='专区描述')),
                ('region_order', models.IntegerField(verbose_name='专区排序')),
                ('region_show', models.IntegerField(choices=[(1, '上架'), (2, '下架')], default=1, verbose_name='上架状态')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('banner_name', models.CharField(max_length=32, verbose_name='轮播图名字')),
                ('banner_url', models.ImageField(blank=True, max_length=500, null=True, upload_to='banner', verbose_name='轮播图片地址')),
                ('banner_order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='pro_photo', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '商品相册管理',
                'verbose_name_plural': '商品相册管理',
            },
        ),
        migrations.CreateModel(
            name='ProCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category_name', models.CharField(max_length=32, verbose_name='分类名')),
                ('category_introduce', models.CharField(blank=True, max_length=200, null=True, verbose_name='分类简介')),
                ('category_order', models.SmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('unit_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='商品单位')),
            ],
            options={
                'verbose_name': '商品单位管理',
                'verbose_name_plural': '商品单位管理',
            },
        ),
        migrations.CreateModel(
            name='ProSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sku_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('sku_introduce', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='商品简介')),
                ('sku_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品价格')),
                ('sku_inventory', models.IntegerField(default=0, verbose_name='商品库存')),
                ('sku_sales_volume', models.IntegerField(blank=True, null=True, verbose_name='商品销量')),
                ('sku_logo', models.ImageField(blank=True, max_length=500, null=True, upload_to='pro_logo', verbose_name='商品LOGO地址')),
                ('sku_show', models.IntegerField(choices=[(1, '上架'), (2, '下架')], default=1, verbose_name='上架状态')),
                ('sku_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProCategory', verbose_name='商品分类id')),
            ],
            options={
                'verbose_name': '商品SKU管理',
                'verbose_name_plural': '商品SKU管理',
            },
        ),
        migrations.CreateModel(
            name='ProSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('spu_name', models.CharField(max_length=32, verbose_name='商品spu名')),
                ('spu_introduce', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品spu详情')),
            ],
            options={
                'verbose_name': '商品SPU管理',
                'verbose_name_plural': '商品SPU管理',
            },
        ),
        migrations.AddField(
            model_name='prosku',
            name='sku_spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProSPU', verbose_name='商品spuid'),
        ),
        migrations.AddField(
            model_name='prosku',
            name='sku_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProductUnit', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='photo_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProSKU', verbose_name='图片sku_id'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProSKU', verbose_name='轮播sku_id'),
        ),
        migrations.AddField(
            model_name='activityregion',
            name='region_sku',
            field=models.ManyToManyField(to='production.ProSKU', verbose_name='商品'),
        ),
    ]
